// import { Roboto } from "@next/font/google";

// const kanit = Roboto({
//   subsets: ["latin"],
//   display: "swap",
//   weight: "500",
// });
import localfont from "next/font/local";

const myFont = localfont({
  src: [
    {
      path: "../../public/fonts/anakotmai-medium.woff2",
    },
  ],
});

// import { Kanit } from "next/font/google";
import Header from "./components/Header";

import "./globals.css";
import HeroSection from "./components/HeroSection";

// const kanit = Kanit({
//   subsets: ["thai"],
//   display: "swap",
//   weight: ["300", "500", "700", "600"],
// });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-slate-50`}>
        <Header />
        <main className="max-w-7xl  mx-auto w-full">{children}</main>
      </body>
    </html>
  );
}
